---
CC:       /opt/toolchains/llvm37/bin/clang
CXX:      /opt/toolchains/llvm37/bin/clang++
CFLAGS:   [ -fno-omit-frame-pointer, -fno-common, -g, --gcc-toolchain=/usr, ]
CXXFLAGS: [ -fno-omit-frame-pointer, -fno-common, -g, --gcc-toolchain=/usr, ]
LDFLAGS:  [ --gcc-toolchain=/usr ]

build_variants:
    release:    []
    debug:      []
    asan:       [ "-fsanitize=address", ]
    asan+ubsan: [ "-fsanitize=address,undefined", "-fno-sanitize=shift,vptr,function", "-DQT_NO_QOBJECT_CHECK", ]
    tsan:       [ "-fsanitize=thread", "-DQT_NO_QOBJECT_CHECK", ]
