---
CC:       /opt/toolchains/llvm36-gcc49/bin/clang
CXX:      /opt/toolchains/llvm36-gcc49/bin/clang++
CFLAGS:   [ -fno-omit-frame-pointer, -fno-common, -g, --gcc-toolchain=/usr, ]
CXXFLAGS: [ -fno-omit-frame-pointer, -fno-common, -g, --gcc-toolchain=/usr, ]
LDFLAGS:  [ --gcc-toolchain=/usr ]

build_variants:
    release:    []
    asan:       [ -fsanitize=address ]
    tsan:       [ -fsanitize=thread ]
